server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    format-sql: true

  datasource:
    data-username: sa
    data-password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    date-format: yyyy-MM-dd

#com.fasterxml.jackson.databind.util.ISO8601DateFormat

#Rabbitmq Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#Redis Configuration
  cache:
    type: redis
    redis:
      time-to-live: 30000ms

  redis:
    host: localhost
    port: 6379

#Queue details
rabbitmq:
  order:
    exchange: ORDER.EXCHANGE
    queue: ORDER.CREATE.QUEUE
    routingKey: ORDER.CREATE.QUEUE
    retryExchange: DLQ.ORDER.EXCHANGE


# Keep the connection alive if idle for a long time (needed in production)
#spring.datasource.testWhileIdle=true
#spring.datasource.validationQuery=SELECT 1