server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  datasource:
    data-username: sa
    data-password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    date-format: yyyy-MM-dd
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  order:
    exchange: ORDER.EXCHANGE
    queue: ORDER.CREATE.QUEUE
    routingKey: ORDER.CREATE.QUEUE


# Keep the connection alive if idle for a long time (needed in production)
#spring.datasource.testWhileIdle=true
#spring.datasource.validationQuery=SELECT 1